name: Build Android App

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build android app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repositor
        uses: actions/checkout@v4
    
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: |
          flutter build apk --release

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
